# Generated by Django 2.2.2 on 2019-06-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['user', 'bio']},
        ),
    ]
